spring:
  application:
    name: sync-service
  data:
    mongodb:
      # Inject URI via env variables configured in Secret Manager
      uri: ${MONGO_URI:mongodb+srv://tekchandkumarsharma_db_user:cjT0yC1YwzwHY5aw@cloudeagle.f4fnmov.mongodb.net/sync-db?appName=CloudEagle}
server:
  port: 8080
